#! /bin/sh

diana list > /dev/null 2>&1

if [ $? -eq 0 ] ; then
    print '%s.\n' 'The daemon is already running' >&2
    exit 1
fi

DOWNLOAD_DIR=${1:-${XDG_DOWNLOAD_DIR:-${HOME}}}
HASHES_FILE=${XDG_DATA_HOME:-${HOME}/.local/share}/diana.lst
BACKUP_HASHES=${HASHES_FILE}.bak

[ ! -e "$HASHES_FILE" -a -e "$BACKUP_HASHES" ] && mv "$BACKUP_HASHES" "$HASHES_FILE"

tmp_file=$(mktemp)
sort -u "$HASHES_FILE" > "$tmp_file"
cp "$tmp_file" "$HASHES_FILE"
rm "$tmp_file"

aria2c -D --enable-rpc -j 13 -d "$DOWNLOAD_DIR"

for line in $(cat "$HASHES_FILE") ; do
    rhsh=${line%:*}
    sel=${line#*:}
    hsh=${rhsh#_}

    for tor in "$DOWNLOAD_DIR"/*.torrent ; do
        match=$(aria2c -S "$tor" | grep -m 1 "$hsh")
        if [ -n "$match" ] ; then
            printf '%s\n' "$tor"
            gid=$(diana --select-file="$sel" add "$tor")
            [ $? -ne 0 ] && exit 1
            case $rhsh in
                _*)
                    diana pause $gid
                    ;;
            esac
        fi
    done
done

mv "$HASHES_FILE" "$BACKUP_HASHES"
